name: RunAwsTerraformTests

on: [push, pull_request]

jobs:
  # Install and cache dependencies
  cache:
    name: Caching
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: cache
        id: cache
        uses: actions/cache@v2
        with:
          path: '~/.cache'
          key: 'awstestcache'
      - name: Download
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          bin/install-aws-test

  test:
    name: Unit test
    runs-on: ubuntu-latest
    needs: cache
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: 'true'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.cache.outputs.dir }}
        key: 'awstestcache'
    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install junit2html
    - name: Test
      run: |
        bin/run-tests TestAccAWSSQSQueue
    - name: "Create report"
      run: |
        bin/create-report
        bin/create-report-html
        cat build/report.html
