name: RunAwsTerraformTests

on: [push, pull_request]

jobs:
  cache:
    name: Caching
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - run: go version
      - name: cache
        id: cache
        uses: actions/cache@v2
        with:
          path: '~/.cache'
          key: 'awstestcache'
      - name: Download
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          bin/install-aws-test

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: cache
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: 'true'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: cache
      uses: actions/cache@v2
      with:
        path: '~/.cache'
        key: 'awstestcache'
    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Start MotoServer
      run: |
        cd moto
        python setup.py sdist
        docker run --rm -t --name motoserver -e TEST_SERVER_MODE=true -e AWS_SECRET_ACCESS_KEY=server_secret -e AWS_ACCESS_KEY_ID=server_key -v `pwd`/moto:/moto -p 5000:5000 -v /var/run/docker.sock:/var/run/docker.sock python:3.7-buster /moto/travis_moto_server.sh &
        python wait_for.py
        cd ..
    - name: Test
      run: |
        bin/run-tests -i moto-tests.success.txt
    - name: "Create report"
      run: |
        bin/create-report
        bin/create-report-cli
